<a href="https://colab.research.google.com/github/skywalker0803r/deep-learning-ian-goodfellow/blob/master/R2D2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
class R2D2(nn.Module):
  def __init__(self,obs_size,n_actions):
    super().__init__()
    self.l1 = nn.Linear(obs_size,128)
    self.l2 = nn.LSTMCell(128,128)
    self.l3 = nn.Linear(128,n_actions)
    self.hx = None
    self.cx = None
  
  def forward(self,x):
    x = torch.tanh(self.l1(x))
    if self.hx is None:
      self.hx = torch.zeros((x.size()[0],128))
      self.cx = torch.zeros((x.size()[0],128))
    self.hx, self.cx = self.l2(x, (self.hx, self.cx))
    x = torch.tanh(self.hx)
    x = torch.tanh(self.l3(x))
    return x

In [3]:
class MLP(nn.Module):
  def __init__(self,obs_size,n_actions):
    super().__init__()
    self.l1 = nn.Linear(obs_size,128)
    self.l2 = nn.Linear(128,n_actions)
  
  def forward(self,x):
    x = torch.tanh(self.l1(x))
    x = torch.tanh(self.l2(x))
    return x

In [4]:
actor1 = R2D2(10,1)
actor2 = MLP(10,1)
x = torch.rand((1,10))

# R2D2(每次結果都不一樣)

In [5]:
for i in range(3):
  print(actor1(x))

tensor([[-0.0702]], grad_fn=<TanhBackward>)
tensor([[-0.0650]], grad_fn=<TanhBackward>)
tensor([[-0.0625]], grad_fn=<TanhBackward>)


# MLP(每次結果都一樣)

In [6]:
for i in range(3):
  print(actor2(x))

tensor([[-0.1362]], grad_fn=<TanhBackward>)
tensor([[-0.1362]], grad_fn=<TanhBackward>)
tensor([[-0.1362]], grad_fn=<TanhBackward>)
